language: node_js # node环境
node_js: lts/*
install:
  - yarn
script:
  - yarn build # 执行命令

after_success:
  - cd src/.vuepress/dist
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add .
  - git commit -m "Build $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:master